language: cpp
script: ./launch-ci

addons:
  homebrew:
    packages:
      - sdl2
      - sdl2_image
      - glm
      - ninja
      - cmake
      - googletest
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libglm-dev
      - libgl1-mesa-dev
      - ninja-build
      - cmake
      - g++
      - libgtest-dev
      - m4

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      dist: focal

before_install:
  - eval "${MATRIX_EVAL}"
