language: cpp
script: make -f macos.Makefile

addons:
  homebrew:
    packages:
      - sdl2
      - sdl2_image
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libglm-dev
      - libgl1-mesa-dev

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      dist: xenial

before_install:
  - eval "${MATRIX_EVAL}"
