language: cpp
script: make -f macos.Makefile

addons:
  homebrew:
    packages:
      - sdl2
      - sdl2_image

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
